import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-alcohol-excise-tax-drawback",
  "engine": "recovery",
  "title": "Alcohol Excise Tax Drawback",
  "shortTitle": "Alcohol Excise Tax Drawback",
  "tagline": "Recover federal and state excise tax on exported, transferred, returned, or destroyed alcohol products.",
  "industry": "Beverage Tax Recovery",
  "buyer": "Brewers, distillers, wineries, and exporters",
  "uiPort": 4689,
  "apiPort": 5689,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Alcohol Excise Tax Drawback converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds in one accountable workflow. Recover federal and state excise tax on exported, transferred, returned, or destroyed alcohol products.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Alcohol Excise Tax Drawback evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("producer-permit-registry","AET01","Producer permit registry","Execute producer permit registry using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed producer permit registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Producer permit registry Reference","text","AET01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("product-formula-registry","AET02","Product formula registry","Execute product formula registry using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed product formula registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Product formula registry Reference","text","AET02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("production-lot-tracking","AET03","Production lot tracking","Execute production lot tracking using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed production lot tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Production lot tracking Reference","text","AET03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("taxpaid-removal-ingestion","AET04","Taxpaid removal ingestion","Execute taxpaid removal ingestion using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed taxpaid removal ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Taxpaid removal ingestion Reference","text","AET04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("bonded-transfer-control","AET05","Bonded transfer control","Execute bonded transfer control using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed bonded transfer control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Bonded transfer control Reference","text","AET05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("export-shipment-matching","AET06","Export shipment matching","Execute export shipment matching using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed export shipment matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Export shipment matching Reference","text","AET06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("proof-of-export-evidence","AET07","Proof-of-export evidence","Execute proof-of-export evidence using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed proof-of-export evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Proof-of-export evidence Reference","text","AET07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("destruction-loss-evidence","AET08","Destruction loss evidence","Execute destruction loss evidence using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed destruction loss evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Destruction loss evidence Reference","text","AET08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("rate-and-credit-calculation","AET09","Rate and credit calculation","Execute rate and credit calculation using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed rate and credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Rate and credit calculation Reference","text","AET09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("claim-eligibility","AET10","Claim eligibility","Execute claim eligibility using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed claim eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Claim eligibility Reference","text","AET10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("statute-deadline-monitoring","AET11","Statute deadline monitoring","Execute statute deadline monitoring using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed statute deadline monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Statute deadline monitoring Reference","text","AET11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("drawback-claim-preparation","AET12","Drawback claim preparation","Execute drawback claim preparation using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed drawback claim preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Drawback claim preparation Reference","text","AET12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("agency-query-workflow","AET13","Agency query workflow","Execute agency query workflow using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed agency query workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Agency query workflow Reference","text","AET13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("refund-reconciliation","AET14","Refund reconciliation","Execute refund reconciliation using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed refund reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Refund reconciliation Reference","text","AET14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]}),
feature("product-market-analytics","AET15","Product market analytics","Execute product market analytics using production records, taxpaid removals, formulas, transfers, exports, destructions, excise returns, proof of export, claims, and refunds.","Produce a governed product market analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Shipment Lot","text","Producer / Shipment Lot · Standard Case"],["caseReference","Product market analytics Reference","text","AET15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1140000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1379400],["domainDriver","Product Type","select","Beer",["Beer","Wine","Distilled spirits"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Producer permit registry case","Product formula registry case","Production lot tracking case","Taxpaid removal ingestion case","Bonded transfer control case"]})
]);
